# Generated by Django 5.2 on 2025-05-03 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0002_alter_booking_booking_id_alter_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_bookings', to='beauty_app.discount'),
        ),
    ]
