# Generated by Django 5.2 on 2025-05-06 00:27

import beauty_app.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0005_sale_payment_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalServiceSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[beauty_app.validators.discount_validator])),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_services', to='beauty_app.sale')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beauty_app.service')),
                ('service_discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beauty_app.discount')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
