# Generated by Django 5.2 on 2025-05-06 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0006_additionalservicesale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalServiceSale',
        ),
    ]
