# Generated by Django 5.2 on 2025-05-07 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0010_audit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audit',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='audit',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='message',
        ),
        migrations.AddField(
            model_name='audit',
            name='model_name',
            field=models.CharField(default=datetime.datetime(2025, 5, 7, 13, 22, 52, 695455, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audit',
            name='object_repr',
            field=models.CharField(default=datetime.datetime(2025, 5, 7, 13, 23, 17, 698551, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audit',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10),
        ),
        migrations.AlterField(
            model_name='audit',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='object_id',
            field=models.CharField(max_length=100),
        ),
    ]
