# Generated by Django 5.2 on 2025-05-07 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0011_alter_audit_options_remove_audit_content_type_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audit',
            options={},
        ),
        migrations.AddField(
            model_name='audit',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='audit',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
