# Generated by Django 5.2 on 2025-05-08 10:56

import beauty_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0013_bookingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='mail@gmail.com', max_length=254, validators=[beauty_app.validators.email_validator]),
            preserve_default=False,
        ),
    ]
