# Generated by Django 5.2 on 2025-05-10 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0014_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'WORKER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('ADMIN', 'Admin'), ('SUPERADMIN', 'Super Admin'), ('WORKER', 'Service Provider')], max_length=10),
        ),
    ]
