# Generated by Django 5.2 on 2025-05-10 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0015_booking_assigned_worker_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary provider for this booking')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_assignments', to='beauty_app.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_assignments', to='beauty_app.service')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('booking', 'service_provider', 'service')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='service_providers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'WORKER'}, related_name='service_provider_assigned_bookings', through='beauty_app.BookingServiceProvider', to=settings.AUTH_USER_MODEL),
        ),
    ]
