# Generated by Django 5.2 on 2025-05-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0016_bookingserviceprovider_booking_service_providers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service_providers',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='assigned_worker',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('ADMIN', 'Admin'), ('SUPERADMIN', 'Super Admin')], max_length=10),
        ),
        migrations.DeleteModel(
            name='BookingServiceProvider',
        ),
    ]
