# Generated by Django 5.2 on 2025-05-10 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0017_remove_booking_service_providers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='therapist',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'STAFF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_additional_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='therapist',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'STAFF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ServiceTherapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapists', to='beauty_app.service')),
                ('therapist', models.ForeignKey(limit_choices_to={'user_type': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('service', 'therapist')},
            },
        ),
    ]
