# Generated by Django 5.2 on 2025-05-10 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0018_additionalservice_therapist_booking_therapist_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceTherapist',
        ),
    ]
