# Generated by Django 5.2 on 2025-05-11 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0020_bookingtherapist_servicetherapist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='primary_service',
            field=models.ForeignKey(blank=True, help_text='The primary service this staff member provides', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_staff', to='beauty_app.service'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('ADMIN', 'Admin'), ('SUPERADMIN', 'Super Admin'), ('STAFFLEVEL2', 'Common Staff')], max_length=20),
        ),
    ]
