# Generated by Django 5.2 on 2025-05-12 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0022_bookingserviceassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingtherapist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bookingtherapist',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='bookingtherapist',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingtherapist',
            name='service',
        ),
        migrations.RemoveField(
            model_name='bookingtherapist',
            name='therapist',
        ),
        migrations.CreateModel(
            name='BookingTherapistAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True, help_text='Whether this therapist is the primary provider for the booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_therapists', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_assignments', to='beauty_app.booking')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
                'unique_together': {('booking', 'therapist')},
            },
        ),
        migrations.DeleteModel(
            name='BookingServiceAssignment',
        ),
        migrations.DeleteModel(
            name='BookingTherapist',
        ),
    ]
