# Generated by Django 5.2 on 2025-05-12 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0023_alter_bookingtherapist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtherapistassignment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beauty_app.service'),
        ),
    ]
