# Generated by Django 5.2 on 2025-05-16 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0025_bookingrequest_preferred_therapist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='preferred_therapist',
        ),
    ]
