# Generated by Django 5.2 on 2025-05-17 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0026_remove_bookingrequest_preferred_therapist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='preferred_therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_booking_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
