# Generated by Django 5.0.6 on 2025-05-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0027_bookingrequest_preferred_therapist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='service',
        ),
        migrations.AddField(
            model_name='discount',
            name='scope',
            field=models.CharField(choices=[('SINGLE', 'Single Service'), ('MULTIPLE', 'Selected Services'), ('ALL', 'All Services')], default='SINGLE', max_length=10),
        ),
        migrations.AddField(
            model_name='discount',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='discounts', to='beauty_app.service'),
        ),
    ]
