# Generated by Django 5.0.6 on 2025-05-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0028_remove_discount_service_discount_scope_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='scope',
        ),
        migrations.AddField(
            model_name='discount',
            name='batch_identifier',
            field=models.CharField(blank=True, help_text='UUID to identify discounts created together', max_length=36, null=True),
        ),
    ]
