# Generated by Django 5.0.6 on 2025-05-21 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0029_remove_discount_scope_discount_batch_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='batch_identifier',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='services',
        ),
        migrations.AddField(
            model_name='discount',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beauty_app.service'),
            preserve_default=False,
        ),
    ]
