# Generated by Django 5.0.6 on 2025-05-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0030_remove_discount_batch_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
