# Generated by Django 5.0.6 on 2025-05-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0031_discount_discount_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='discount_name',
        ),
    ]
