# Generated by Django 5.2 on 2025-05-24 00:01

import beauty_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_app', '0035_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[beauty_app.validators.email_validator]),
        ),
    ]
